=encoding utf8


=head1 NAME

 Angelos::Tutorial - 

=head1 SYNOPSIS


=head1 DESCRIPTION


=head1 HOW TO INSTALL

=head1 HOW TO START

スケルトンの生成
  
    $ angelos generate --name MyApp
    $ cd MyApp

    # ここはModule::SetupのPluginで自動でできるようにする
    $ chmod 700 bin/server

開発サーバーの起動
    $ bin/server

デバッグモードでの起動
    $ ANGELOS_DEBUG=1 bin/server

=head1 HOW TO DEVELOP

=head2 ルーティング
pathとController, actionへのマッピングを規定.
RailsライクなRoutingを規定する

  $ vim conf/routes.pl

    HTTP::Router->define(
        sub {
            $_->match('/')->to( { controller => 'Root', action => 'index' } );
        }   
    );
  
複数のルールを書く場合

    HTTP::Router->define(
        sub {
            $_->match('/')->to( { controller => 'Root', action => 'index' } );
            $_->resources('Book');
        }
    );
  
=head2 Controllerの実装

    package MyApp::Controller::Root;
    use Mouse;
    extends 'Angelos::Controller';
    
    sub index {
       # /share/root/templates/root/index.tt is used
       $c->view('TT')->render;
    }

    __PACKAGE__->meta->make_immutable;
    1;

=head2 Viewの実装
    package MyApp::View::TT;
    use Mouse;
    extends 'Angelos::View::TT';
   
    __PACKAGE__->meta->make_immutable;
    1;
    
=cut



