---
components:
  controller:
    - module: A

plugins:
  controller:
    - module: HTML::Shakan 
#   - module: ActionProfiler
#   - module: DebugHook 

#mixins:
#  request:
#   - module: MobileAgent 

middlewares:
  - module: Static
  - module: Encode 
  - module: Session

database:
  master:
    connect_info:
      - dbi:SQLite:dbname=__path_to(db/testapp.db)__

#  - module: DebugScreen
#  - module: DebugRequest
#  - module: Session
#    config:
#      store:
#        class: HTTP::Session::Store::File
#        config:
#           dir: /tmp/session
#      state:
#        class: HTTP::Session::State::URI
#        config:
#          session_id_name: hoge
#      id: HTTP::Session::ID::SHA1
 
