---
components:
  controller:
    - module: A

plugins:
  #controller:
  #  - module: Dumper
  debug:
    - module: Components

#middlewares:
#  - module: Angelos::Middleware::Profile
#  - module: HTTPx::Middleware::DebugScreen

