---
components:
  controller:
    - module: A

mixins:
  controller:
    - module: Dumper

plugins:
  engine:
   - module: Session

middlewares:
  - module: Angelos::Middleware::Profile
  - module: Angelos::Middleware::DebugRequest
