---
components:
  controller:
    - module: A

plugins:
  engine:
   - module: Session
  controller:
   - module: HookLogger 
   - module: Dumper 

#middlewares:
#  - module: Angelos::Middleware::Profile
#  - module: Angelos::Middleware::DebugRequest
