---
components:
  controller:
    - module: A

mixins:
  controller:
    - module: Dumper
  debug:
    - module: Components

#plugins:
#  engine:
#   - module: Session

#middlewares:
#  - module: Angelos::Middleware::Profile
#  - module: HTTPx::Middleware::DebugScreen

