--- !ditz.rubyforge.org,2008-03-06/project 
name: angelos
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: angelos
- !ditz.rubyforge.org,2008-03-06/component 
  name: controller
- !ditz.rubyforge.org,2008-03-06/component 
  name: model
- !ditz.rubyforge.org,2008-03-06/component 
  name: view
- !ditz.rubyforge.org,2008-03-06/component 
  name: router
- !ditz.rubyforge.org,2008-03-06/component 
  name: dispatcher
- !ditz.rubyforge.org,2008-03-06/component 
  name: middleware 
- !ditz.rubyforge.org,2008-03-06/component 
  name: configloader
- !ditz.rubyforge.org,2008-03-06/component 
  name: Tutorial
- !ditz.rubyforge.org,2008-03-06/component 
  name: script 
- !ditz.rubyforge.org,2008-03-06/component 
  name: testing
- !ditz.rubyforge.org,2008-03-06/component 
  name: flavor

releases: []

