---
components:
  controller:
    - module: A

middlewares:
  - module: Encode
  - module: MethodOverride
  - module: Static

database:
  master:
    connect_info:
      - dbi:SQLite:dbname=__path_to(db/development.db)__


