---
components:
  controller:
    - module: A

plugins:
  engine:
   - module: Session
  controller:
   - module: ActionProfiler

middlewares:
  - module: Angelos::Middleware::DebugRequest
  - module: Angelos::Middleware::Unicode
