---
components:
  controller:
    - module: A

plugins:
  engine:
   - module: Session
  controller:
   - module: ActionProfiler
     config: 
       aaa : bbb
       ccc : ddd

#   - module: DebugHook 

middlewares:
  - module: Angelos::Middleware::DebugRequest
  - module: Angelos::Middleware::Unicode
  - module: Angelos::Middleware::Static
